Disable cosmic to fix conflict in xdg portal
The error was:
error: builder for
'/nix/store/xzprbsfnr4jrx792ma36kh404l14wd3m-user-units.drv' failed with
exit code 1;
last 1 log lines:
> ln: failed to create symbolic link
'/nix/store/5mmyw2cp6a8aj78cj6s2irgfhx5wsbp5-user-units/xdg-desktop-portal-gtk.service':
File exists
For full logs, run 'nix log
/nix/store/xzprbsfnr4jrx792ma36kh404l14wd3m-user-units.drv'.
error: 1 dependencies of derivation
'/nix/store/j815hmcf8k2h6d7jind851mpn4lsgc6q-etc.drv'
failed to build
error: 1 dependencies of derivation
'/nix/store/z10ajrw8s6z2xvsvz5vji5y84jy7717w-nixos-system-kaiki-24.05.20240403.fd281bd.drv'
failed to build